import json
import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

def _base_dir() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    return Path(__file__).resolve().parent.parent


def _get_os() -> str:
    try:
        cfg = json.loads(
            (_base_dir() / "config" / "api_keys.json").read_text(encoding="utf-8")
        )
        return cfg.get("os_system", "windows").lower()
    except Exception:
        return "windows"


def _scripts_dir() -> Path:
    d = Path.home() / ".jarvis" / "reminders"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _sanitise(text: str, max_len: int = 200) -> str:
    return (
        text.replace("\\", "")
            .replace('"', "")
            .replace("'", "")
            .replace("\n", " ")
            .replace("\r", "")
            .strip()
    )[:max_len]

def _write_notify_script(task_name: str, message: str, os_name: str) -> Path:
    script_path = _scripts_dir() / f"{task_name}.py"
    msg_literal = json.dumps(message)  

    if os_name == "windows":
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        from win10toast import ToastNotifier
        ToastNotifier().show_toast("J.A.R.V.I.S Reminder", message, duration=15, threaded=False)
        notified = True
    except Exception:
        pass

if not notified:
    try:
        import subprocess
        subprocess.run(["msg", "*", "/TIME:30", message], check=False)
    except Exception:
        pass

try:
    import winsound
    for freq in [800, 1000, 1200]:
        winsound.Beep(freq, 180)
        import time; time.sleep(0.08)
except Exception:
    pass
"""

    elif os_name == "mac":
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        import subprocess
        script = 'display notification "{{}}" with title "J.A.R.V.I.S Reminder"'.format(
            message.replace('"', '')
        )
        subprocess.run(["osascript", "-e", script], check=False)
    except Exception:
        pass
"""

    else:  # linux
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        import subprocess
        subprocess.run(
            ["notify-send", "--urgency=normal", "--expire-time=15000",
             "J.A.R.V.I.S Reminder", message],
            check=False
        )
    except Exception:
        pass
"""

    script_body = f"""# Auto-generated by J.A.R.V.I.S reminder — do not edit
import sys, os, pathlib
{notify_block}
# Self-delete after firing
try:
    pathlib.Path(__file__).unlink(missing_ok=True)
except Exception:
    pass
"""
    script_path.write_text(script_body, encoding="utf-8")
    script_path.chmod(0o600)   # owner read/write only
    return script_path

def _schedule_windows(target_dt: datetime, task_name: str,
                      script_path: Path, message: str) -> str:
    python_exe = Path(sys.executable)
    pythonw = python_exe.parent / "pythonw.exe"
    if pythonw.exists():
        python_exe = pythonw

    xml_path = _scripts_dir() / f"{task_name}.xml"
    xml_content = (
        '<?xml version="1.0" encoding="UTF-16"?>\n'
        '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\n'
        '  <RegistrationInfo><Description>J.A.R.V.I.S Reminder</Description></RegistrationInfo>\n'
        '  <Triggers><TimeTrigger>\n'
        f'    <StartBoundary>{target_dt.strftime("%Y-%m-%dT%H:%M:%S")}</StartBoundary>\n'
        '    <Enabled>true</Enabled>\n'
        '  </TimeTrigger></Triggers>\n'
        '  <Actions><Exec>\n'
        f'    <Command>{python_exe}</Command>\n'
        f'    <Arguments>"{script_path}"</Arguments>\n'
        '  </Exec></Actions>\n'
        '  <Settings>\n'
        '    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n'
        '    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n'
        '    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n'
        '    <StartWhenAvailable>true</StartWhenAvailable>\n'
        '    <ExecutionTimeLimit>PT5M</ExecutionTimeLimit>\n'
        '    <Enabled>true</Enabled>\n'
        '  </Settings>\n'
        '  <Principals><Principal>\n'
        '    <LogonType>InteractiveToken</LogonType>\n'
        '    <RunLevel>LeastPrivilege</RunLevel>\n'
        '  </Principal></Principals>\n'
        '</Task>'
    )

    xml_path.write_text(xml_content, encoding="utf-16")

    result = subprocess.run(
        ["schtasks", "/Create", "/TN", task_name, "/XML", str(xml_path), "/F"],
        capture_output=True, text=True,
    )

    try:
        xml_path.unlink(missing_ok=True)
    except Exception:
        pass

    if result.returncode != 0:
        script_path.unlink(missing_ok=True)
        err = (result.stderr or result.stdout).strip()
        print(f"[Reminder] ❌ schtasks: {err}")
        return ""  

    return task_name


def _schedule_mac(target_dt: datetime, task_name: str,
                  script_path: Path) -> str:
    agents_dir = Path.home() / "Library" / "LaunchAgents"
    agents_dir.mkdir(parents=True, exist_ok=True)

    label     = f"com.jarvis.reminder.{task_name}"
    plist_path = agents_dir / f"{label}.plist"

    plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>             <string>{label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>{sys.executable}</string>
    <string>{script_path}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Year</key>   <integer>{target_dt.year}</integer>
    <key>Month</key>  <integer>{target_dt.month}</integer>
    <key>Day</key>    <integer>{target_dt.day}</integer>
    <key>Hour</key>   <integer>{target_dt.hour}</integer>
    <key>Minute</key> <integer>{target_dt.minute}</integer>
  </dict>
  <key>RunAtLoad</key>         <false/>
  <key>StandardOutPath</key>   <string>/dev/null</string>
  <key>StandardErrorPath</key> <string>/dev/null</string>
</dict>
</plist>
"""
    plist_path.write_text(plist_content, encoding="utf-8")
    plist_path.chmod(0o644)

    result = subprocess.run(
        ["launchctl", "load", str(plist_path)],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        plist_path.unlink(missing_ok=True)
        script_path.unlink(missing_ok=True)
        print(f"[Reminder] ❌ launchctl: {result.stderr.strip()}")
        return ""

    return label


def _schedule_linux(target_dt: datetime, task_name: str,
                    script_path: Path) -> str:

    if shutil.which("systemd-run"):
        on_calendar = target_dt.strftime("%Y-%m-%d %H:%M:00")
        result = subprocess.run(
            [
                "systemd-run",
                "--user",
                f"--on-calendar={on_calendar}",
                f"--unit={task_name}",
                "--",
                sys.executable, str(script_path),
            ],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            return task_name
        print(f"[Reminder] ⚠️ systemd-run failed: {result.stderr.strip()}, trying 'at'")

    if shutil.which("at"):
        at_time = target_dt.strftime("%H:%M %Y-%m-%d")
        cmd_str = f"{sys.executable} {script_path}\n"
        result  = subprocess.run(
            ["at", at_time],
            input=cmd_str, capture_output=True, text=True,
        )
        if result.returncode == 0:
            return task_name
        print(f"[Reminder] ❌ at: {result.stderr.strip()}")
        return ""

    print("[Reminder] ❌ Neither systemd-run nor at found on this Linux system.")
    return ""

def reminder(
    parameters: dict,
    response=None,
    player=None,
    session_memory=None,
) -> str:

    action = parameters.get("action", "set").strip().lower()
    date_str = parameters.get("date", "").strip()
    time_str = parameters.get("time", "").strip()
    message  = parameters.get("message", "Reminder").strip()
    interval_min = parameters.get("interval_minutes", 0)
    repeat_count = parameters.get("repeat_count", 1)

    # ---- CANCEL ----
    if action == "cancel":
        task_name = parameters.get("task_name", "").strip()
        if not task_name:
            return "I need the task name to cancel. Use 'list' to see active reminders."
        os_name = _get_os()
        try:
            if os_name == "windows":
                result = subprocess.run(
                    ["schtasks", "/End", "/TN", task_name],
                    capture_output=True, text=True, timeout=10
                )
                subprocess.run(
                    ["schtasks", "/Delete", "/TN", task_name, "/F"],
                    capture_output=True, text=True, timeout=10
                )
            elif os_name == "mac":
                label = f"com.jarvis.reminder.{task_name}"
                subprocess.run(["launchctl", "unload", f"{Path.home()}/Library/LaunchAgents/{label}.plist"],
                              capture_output=True, timeout=10)
            else:
                subprocess.run(["systemctl", "--user", "stop", task_name],
                              capture_output=True, timeout=10)
            # Clean up any remaining script files
            script_path = _scripts_dir() / f"{task_name}.py"
            script_path.unlink(missing_ok=True)
            return f"Reminder '{task_name}' cancelled successfully."
        except Exception as e:
            return f"Could not cancel reminder: {e}"

    # ---- LIST ----
    if action == "list":
        os_name = _get_os()
        reminders = []
        try:
            if os_name == "windows":
                result = subprocess.run(
                    ["schtasks", "/Query", "/FO", "CSV"],
                    capture_output=True, text=True, timeout=10
                )
                for line in result.stdout.strip().split("\n")[1:]:
                    if "JARVISReminder" in line:
                        parts = line.split(",")
                        if len(parts) >= 1:
                            reminders.append(parts[0].strip('"\\"'))
            elif os_name == "mac":
                for plist in Path.home().glob("Library/LaunchAgents/com.jarvis.reminder.*.plist"):
                    reminders.append(plist.stem)
        except Exception:
            pass
        if not reminders:
            return "No active reminders found."
        return "Active reminders:\n" + "\n".join(f"  - {r}" for r in reminders)

    # ---- SET (original behavior with repeat support) ----
    if not date_str or not time_str:
        return "I need both a date and a time to set a reminder."

    try:
        target_dt = datetime.strptime(f"{date_str} {time_str}", "%Y-%m-%d %H:%M")
    except ValueError:
        return "I couldn't parse that date or time. Please use YYYY-MM-DD and HH:MM."

    if target_dt <= datetime.now():
        return "That time has already passed — I can't set a reminder in the past."

    os_name    = _get_os()
    safe_msg   = _sanitise(message)
    task_name  = f"JARVISReminder_{target_dt.strftime('%Y%m%d_%H%M%S')}"

    # For repeating reminders, DON'T self-delete the script
    repeating = interval_min > 0 and repeat_count > 1
    try:
        if repeating:
            script_path = _write_repeating_script(task_name, safe_msg, os_name, interval_min, repeat_count)
        else:
            script_path = _write_notify_script(task_name, safe_msg, os_name)
    except Exception as e:
        return f"Could not prepare the reminder script: {e}"

    try:
        if os_name == "windows":
            job_id = _schedule_windows_repeating(target_dt, task_name, script_path, safe_msg, interval_min, repeat_count) if repeating else \
                     _schedule_windows(target_dt, task_name, script_path, safe_msg)
        elif os_name == "mac":
            job_id = _schedule_mac(target_dt, task_name, script_path)
        else:
            job_id = _schedule_linux(target_dt, task_name, script_path)
    except Exception as e:
        script_path.unlink(missing_ok=True)
        print(f"[Reminder] ❌ Scheduling exception: {e}")
        return "Something went wrong while scheduling the reminder."

    if not job_id:
        return "I couldn't register the reminder with the system scheduler."

    if player:
        player.write_log(f"[Reminder] ✅ {date_str} {time_str} — {safe_msg[:40]}{' (repeating: ' + str(repeat_count) + 'x every ' + str(interval_min) + ' min)' if repeating else ''}")

    friendly_time = target_dt.strftime("%B %d at %I:%M %p")
    if repeating:
        return f"Reminder set for {friendly_time}, repeating {repeat_count} times every {interval_min} minute(s). Use 'cancel' action with task_name '{job_id}' to stop."
    return f"Reminder set for {friendly_time}."


def _write_repeating_script(task_name: str, message: str, os_name: str, interval_min: int, repeat_count: int) -> Path:
    """Write a notification script that fires multiple times, tracking progress via a counter file."""
    script_path = _scripts_dir() / f"{task_name}.py"
    counter_path = _scripts_dir() / f"{task_name}.counter"
    msg_literal = json.dumps(message)

    os_block = ""
    if os_name == "windows":
        os_block = f"""
try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
except Exception:
    pass
try:
    from win10toast import ToastNotifier
    ToastNotifier().show_toast("J.A.R.V.I.S Reminder", message, duration=15, threaded=False)
except Exception:
    pass
try:
    import subprocess
    subprocess.run(["msg", "*", "/TIME:30", message], check=False)
except Exception:
    pass
try:
    import winsound
    for freq in [800, 1000, 1200]:
        winsound.Beep(freq, 180)
        import time; time.sleep(0.08)
except Exception:
    pass
"""
    else:
        os_block = f"""
try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
except Exception:
    pass
try:
    import subprocess
    import platform
    if platform.system() == 'Darwin':
        subprocess.run(["osascript", "-e", 'display notification "' + message.replace('"', '') + '" with title "J.A.R.V.I.S Reminder"'], check=False)
    else:
        subprocess.run(["notify-send", "--urgency=normal", "--expire-time=15000", "J.A.R.V.I.S Reminder", message], check=False)
except Exception:
    pass
"""

    script_body = f"""# Auto-generated by J.A.R.V.I.S repeating reminder — do not edit
import json, os, pathlib, sys, time
message = {msg_literal}
{os_block}
# Track repetitions via counter file
counter_path = r"{counter_path}"
count = json.loads(pathlib.Path(counter_path).read_text()) if pathlib.Path(counter_path).exists() else 0
count += 1
pathlib.Path(counter_path).write_text(json.dumps(count))
# If this was the last repetition, schedule self-deletion
if count >= {repeat_count}:
    pathlib.Path(counter_path).unlink(missing_ok=True)
    pathlib.Path(__file__).unlink(missing_ok=True)
"""
    script_path.write_text(script_body, encoding="utf-8")
    script_path.chmod(0o600)
    return script_path


def _schedule_windows_repeating(target_dt: datetime, task_name: str, script_path: Path, message: str, interval_min: int, repeat_count: int) -> str:
    """Schedule a repeating task using Windows Task Scheduler with repetition pattern."""
    python_exe = Path(sys.executable)
    pythonw = python_exe.parent / "pythonw.exe"
    if pythonw.exists():
        python_exe = pythonw

    # Create a task that repeats every interval_min for (interval_min * repeat_count) duration
    duration_min = interval_min * repeat_count
    duration_str = f"PT{duration_min}M"
    interval_str = f"PT{interval_min}M"

    xml_path = _scripts_dir() / f"{task_name}.xml"
    xml_content = (
        '<?xml version="1.0" encoding="UTF-16"?>\n'
        '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\n'
        '  <RegistrationInfo><Description>J.A.R.V.I.S Repeating Reminder</Description></RegistrationInfo>\n'
        '  <Triggers>\n'
        '    <TimeTrigger>\n'
        f'      <StartBoundary>{target_dt.strftime("%Y-%m-%dT%H:%M:%S")}</StartBoundary>\n'
        f'      <Repetition><Interval>{interval_str}</Interval><Duration>{duration_str}</Duration><StopAtDurationEnd>true</StopAtDurationEnd></Repetition>\n'
        '      <Enabled>true</Enabled>\n'
        '    </TimeTrigger>\n'
        '  </Triggers>\n'
        '  <Actions><Exec>\n'
        f'    <Command>{python_exe}</Command>\n'
        f'    <Arguments>"{script_path}"</Arguments>\n'
        '  </Exec></Actions>\n'
        '  <Settings>\n'
        '    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n'
        '    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n'
        '    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n'
        '    <StartWhenAvailable>true</StartWhenAvailable>\n'
        f'    <ExecutionTimeLimit>{duration_str}</ExecutionTimeLimit>\n'
        '    <Enabled>true</Enabled>\n'
        '  </Settings>\n'
        '  <Principals><Principal>\n'
        '    <LogonType>InteractiveToken</LogonType>\n'
        '    <RunLevel>LeastPrivilege</RunLevel>\n'
        '  </Principal></Principals>\n'
        '</Task>'
    )

    xml_path.write_text(xml_content, encoding="utf-16")

    result = subprocess.run(
        ["schtasks", "/Create", "/TN", task_name, "/XML", str(xml_path), "/F"],
        capture_output=True, text=True,
    )

    try:
        xml_path.unlink(missing_ok=True)
    except Exception:
        pass

    if result.returncode != 0:
        script_path.unlink(missing_ok=True)
        err = (result.stderr or result.stdout).strip()
        print(f"[Reminder] ❌ schtasks repeating: {err}")
        return ""

    return task_name
